// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {updater} from '../models';

export function AddModel(arg1:string,arg2:models.Model):Promise<void>;

export function CheckForUpdates():Promise<updater.UpdateInfo>;

export function ClearAllData():Promise<void>;

export function CreateProvider(arg1:models.Provider):Promise<models.Provider>;

export function DeleteModel(arg1:string,arg2:string):Promise<void>;

export function DeleteProvider(arg1:string):Promise<void>;

export function ExportData():Promise<boolean>;

export function FetchModels(arg1:string,arg2:string,arg3:any):Promise<models.FetchModelsResult>;

export function GetAllProviders():Promise<Array<models.Provider>>;

export function GetCrashReporting():Promise<boolean>;

export function GetDataDir():Promise<string>;

export function GetInitError():Promise<string>;

export function GetLogDir():Promise<string>;

export function GetProvider(arg1:string):Promise<models.Provider>;

export function GetTheme():Promise<string>;

export function GetVersion():Promise<string>;

export function HasInitError():Promise<boolean>;

export function ImportData(arg1:string):Promise<models.ImportResult>;

export function SaveProviders(arg1:Array<models.Provider>):Promise<void>;

export function SetCrashReporting(arg1:boolean):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function TransformFetchedModel(arg1:models.FetchedModel):Promise<models.Model>;

export function UpdateCredentials(arg1:string,arg2:Array<string>):Promise<void>;

export function UpdateModel(arg1:string,arg2:string,arg3:models.Model):Promise<void>;

export function UpdateProvider(arg1:string,arg2:models.Provider):Promise<void>;
