// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddModel(arg1, arg2) {
  return window['go']['main']['App']['AddModel'](arg1, arg2);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearAllData() {
  return window['go']['main']['App']['ClearAllData']();
}

export function CreateProvider(arg1) {
  return window['go']['main']['App']['CreateProvider'](arg1);
}

export function DeleteModel(arg1, arg2) {
  return window['go']['main']['App']['DeleteModel'](arg1, arg2);
}

export function DeleteProvider(arg1) {
  return window['go']['main']['App']['DeleteProvider'](arg1);
}

export function ExportData() {
  return window['go']['main']['App']['ExportData']();
}

export function FetchModels(arg1, arg2, arg3) {
  return window['go']['main']['App']['FetchModels'](arg1, arg2, arg3);
}

export function GetAllProviders() {
  return window['go']['main']['App']['GetAllProviders']();
}

export function GetCrashReporting() {
  return window['go']['main']['App']['GetCrashReporting']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetFollowSystemTheme() {
  return window['go']['main']['App']['GetFollowSystemTheme']();
}

export function GetInitError() {
  return window['go']['main']['App']['GetInitError']();
}

export function GetLogDir() {
  return window['go']['main']['App']['GetLogDir']();
}

export function GetProvider(arg1) {
  return window['go']['main']['App']['GetProvider'](arg1);
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HasInitError() {
  return window['go']['main']['App']['HasInitError']();
}

export function ImportData(arg1) {
  return window['go']['main']['App']['ImportData'](arg1);
}

export function SaveProviders(arg1) {
  return window['go']['main']['App']['SaveProviders'](arg1);
}

export function SetCrashReporting(arg1) {
  return window['go']['main']['App']['SetCrashReporting'](arg1);
}

export function SetFollowSystemTheme(arg1) {
  return window['go']['main']['App']['SetFollowSystemTheme'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function TransformFetchedModel(arg1) {
  return window['go']['main']['App']['TransformFetchedModel'](arg1);
}

export function UpdateCredentials(arg1, arg2) {
  return window['go']['main']['App']['UpdateCredentials'](arg1, arg2);
}

export function UpdateModel(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateModel'](arg1, arg2, arg3);
}

export function UpdateProvider(arg1, arg2) {
  return window['go']['main']['App']['UpdateProvider'](arg1, arg2);
}
